<?php

declare(strict_types=1);

namespace Padosoft\AskMyDocsConnectorImap\Imap;

final class MessageFilter
{
    /** @param array<string,mixed> $config */
    public function __construct(private array $config) {}

    public function passes(ImapMessage $m): bool
    {
        if (($this->config['only_flagged'] ?? false) === true && ! in_array('\\Flagged', $m->flags, true)) {
            return false;
        }
        if (($this->config['only_unseen'] ?? false) === true && in_array('\\Seen', $m->flags, true)) {
            return false;
        }
        if (($this->config['skip_auto_generated'] ?? false) === true && $this->isAutoGenerated($m)) {
            return false;
        }
        if (! $this->senderPasses($m->fromEmail)) {
            return false;
        }
        if (! $this->subjectPasses($m->subject)) {
            return false;
        }
        if (! $this->recipientPasses($m)) {
            return false;
        }

        return true;
    }

    private function senderPasses(string $from): bool
    {
        $include = array_map('strtolower', (array) ($this->config['senders']['include'] ?? []));
        $exclude = array_map('strtolower', (array) ($this->config['senders']['exclude'] ?? []));
        $emails = [strtolower($from)];

        if ($this->matchesAny($emails, $exclude)) {
            return false;
        }
        if ($include !== [] && ! $this->matchesAny($emails, $include)) {
            return false;
        }

        return true;
    }

    private function recipientPasses(ImapMessage $m): bool
    {
        $include = array_map('strtolower', (array) ($this->config['recipients']['include'] ?? []));
        $exclude = array_map('strtolower', (array) ($this->config['recipients']['exclude'] ?? []));

        if ($include === [] && $exclude === []) {
            return true;
        }

        /** @var list<string> $emails */
        $emails = [];
        foreach ([...$m->to, ...$m->cc] as $addr) {
            $emails[] = strtolower((string) $addr['email']);
        }

        if ($this->matchesAny($emails, $exclude)) {
            return false;
        }
        if ($include !== [] && ! $this->matchesAny($emails, $include)) {
            return false;
        }

        return true;
    }

    /**
     * Returns true if ANY address in $addresses matches ANY needle.
     * A needle can be a full address (exact) or a bare domain (matches @domain suffix).
     *
     * @param  array<string>  $addresses  already lower-cased
     * @param  array<string>  $needles  already lower-cased
     */
    private function matchesAny(array $addresses, array $needles): bool
    {
        foreach ($addresses as $address) {
            foreach ($needles as $needle) {
                if ($this->addrMatches($address, $needle)) {
                    return true;
                }
            }
        }

        return false;
    }

    private function addrMatches(string $address, string $needle): bool
    {
        // needle is a full address or a bare domain
        return $address === $needle || str_ends_with($address, '@'.$needle);
    }

    private function subjectPasses(string $subject): bool
    {
        $subject = mb_strtolower($subject);
        $include = (array) ($this->config['subject']['include_keywords'] ?? []);
        $exclude = (array) ($this->config['subject']['exclude_keywords'] ?? []);

        foreach ($exclude as $kw) {
            if ($kw !== '' && str_contains($subject, mb_strtolower((string) $kw))) {
                return false;
            }
        }
        if ($include !== []) {
            foreach ($include as $kw) {
                if ($kw !== '' && str_contains($subject, mb_strtolower((string) $kw))) {
                    return true;
                }
            }

            return false;
        }

        return true;
    }

    private function isAutoGenerated(ImapMessage $m): bool
    {
        $headers = array_change_key_case($m->rawHeaders, CASE_LOWER);
        $precedence = strtolower((string) ($headers['precedence'] ?? ''));
        if (in_array($precedence, ['bulk', 'list', 'junk'], true)) {
            return true;
        }
        if (isset($headers['auto-submitted']) && strtolower((string) $headers['auto-submitted']) !== 'no') {
            return true;
        }
        if (isset($headers['list-unsubscribe'])) {
            return true;
        }

        return false;
    }
}
